name: 🐛 Bug Report
description: Report an issue related to documentation
labels: ["bug", "needs triage"]
assignees:
  - mkeithX
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report.
        [Learn more](https://mkeithx.pages.dev/community/contributing#issues).

  - type: dropdown
    id: issue
    attributes:
      label: Issue category
      description: What's the issue about?
      multiple: false
      options:
        - Undocumented API
        - Elaboration needed on a particular topic
        - Outdated or incorrect information
        - Formatting or readability improvement
        - Others
    validations:
      required: true     

  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of what the issue is.
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps you've taken so far.
      placeholder: |
        1. I've checked ...
        2. Also validated through ...
        3. Including this ...
        4. To support this ...
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/mkeithX/mkeithx.github.io/blob/main/CONTRIBUTING.md)
      options:
        - label: I agree to follow this project's Code of Conduct.
          required: true
