import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  cosmicSidebar: [
    "genesis",
    "timeline",
    "forces-and-mysteries",
    {
      type: "category",
      label: "The Solar System",
      collapsed: false,
      collapsible: true,
      link: {
        type: 'doc',
        id: 'solar-system/index',
      },
      items: [
        'solar-system/sun',
        {
          type: 'category',
          label: 'Planets',
          collapsed: true,
          collapsible: true,
          link: {
            type: 'doc',
            id: 'solar-system/planets/index',
          },
          items: [
            'solar-system/planets/mercury',
            'solar-system/planets/venus',
            'solar-system/planets/earth',
            'solar-system/planets/mars',
            'solar-system/planets/jupiter',
            'solar-system/planets/saturn',
            'solar-system/planets/uranus',
            'solar-system/planets/neptune',
            'solar-system/planets/pluto',
            'solar-system/planets/planet-x'
          ]
        },
        {
          type: 'category',
          label: 'Moons',
          collapsed: true,
          collapsible: true,
          link: {
            type: 'doc',
            id: 'solar-system/moons/index',
          },
          items: [
            'solar-system/moons/phases-of-the-moon',
            'solar-system/moons/mars-moons',
          ]
        },
        {
          type: 'category',
          label: 'Comets and Asteroids',
          collapsed: true,
          collapsible: true,
          link: {
            type: 'doc',
            id: 'solar-system/comets-and-asteroids/index'
          },
          items: [
            'solar-system/comets-and-asteroids/halleys-comet',
            'solar-system/comets-and-asteroids/shoemaker-levy-9'
          ]
        }
      ],


    },
    {
      type: "category",
      label: "Astrophysics",
      items: [
        {
          type: "autogenerated",
          dirName: "astrophysics",
        },
      ],
      link: {
        type: 'generated-index',
        title: 'Astrophysics',
        slug: '/astrophysics',
        description: 'Delving into the properties and behaviors of celestial bodies within the cosmos 🔭',
        image: 'https://imgur.com/x2Hik8D.png'
      }
    },
    {
      type: "category",
      label: "Legacies & Contributions",
      collapsed: true,
      link: {
        type: 'doc',
        id: 'legacy/index',
      },
      items: [
        'legacy/women-in-physics',
        'legacy/the-golden-record',
        'legacy/standard-model',
        'legacy/exploring-principia',
        'legacy/special-general-relativity',
        'legacy/cherenkov-radiation',
        'legacy/kardashev-scale',
      ]
    },
        {
      type: 'html',
      value: '<a href="https://eyes.nasa.gov/apps/solar-system/#/home" target="_blank"><img src="/img/space/NASA_logo.svg" alt="beta" height="45"/></a>',
      defaultStyle: true,
      // href: 'https://example.com',
    },
  ],
};

export default sidebars;
