import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Sidebar configuration for organized documentation.
 * Includes categories, subcategories, and documents.
 */
const sidebars: SidebarsConfig = {
  mySidebar: [
    // Root-level documents
    "introduction",
    "quick-links",
    
    {
      type: "category",
      label: "System Administration",
      collapsed: false,
      link: {
        type: "generated-index",
        slug: "/system-administration",
        description: "Guides and best practices for System Admin. ",
      },
      items: [
        {
          type: "autogenerated",
          dirName:"system-administration"
        },
      ],
    },
    {
      type: "category",
      label: "Configuration",
      collapsed: true,
      link: { type: "doc", id: "configs/index" },
      items: [
        "configs/guides/docs/create-doc",
        "configs/guides/docs/docs-create-page",
        "configs/guides/docs/blog",
        {
          type: "category",
          label: "Deployment",
          collapsed: true,
          link: { type: "generated-index", slug: "/deployment", description: "Deployment configuration (GitHub & Cloudflare)" },
          items: [
            "configs/guides/deployment/deploy-cloudflare",
            "configs/guides/deployment/deploy-github",
          ],
        },

        {
          type: "category",
          label: "Plugins",
          collapsed: true,
          link: { type: "generated-index", slug: "/plugins" },
          items: ["configs/guides/plugins/plugins-algolia"],
        },

        {
          type: "category",
          label: "Configs",
          collapsed: true,
          link: { type: "generated-index", slug: "/guides", description: "Guidelines for creating docs, pages, and blog articles." },
          items: [],
        },
      ],
   
    },
    {
      type: "category",
      label: "Additional resources",
      collapsed: true,
      items: [
        {
          type: "category",
          label: "Workarounds",
          collapsed: true,
          link: { type: "doc", id: "how-tos/index" },
          items: [
            "how-tos/fix-ms-teams",
            "how-tos/fix-connectivity",
            "how-tos/fix-windows-hardware-issues",
          ],
        },

        {
          type: "category",
          label: "Gists",
          link: { type: "generated-index", slug: "/gists", description: "Quick examples, utilities, and demos." },
          items: [
            "gists/gists-git",
            "gists/gists-powershell",
            {
              type: "category",
              label: "Extras",
              collapsed: true,
              link: { type: "generated-index", slug: "/extras" },
              items: ["gists/extras/quick-responses", "gists/extras/misc"],
            },
          ],
        },
      ],
    },
    'downloads',
    'speedtest',
  ],
  
  learnSidebar: [
    {
      type: "autogenerated",
      dirName: "learn"
    },
    "learn",
  ]

};

export default sidebars;
