import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Sidebar configuration for organized documentation.
 * Includes categories, subcategories, and documents.
 */
const sidebars: SidebarsConfig = {
  mySidebar: [
    // Root-level documents
    "introduction",

    {
      type: "category",
      label: "Quick Links",
      collapsed: false,
      items: [
        "cli",
        "downloads",
        "aka-ms",
        "mailbox-archive",
        {
          type: "category",
          label: "How-Tos",
          collapsed: true,
          link: { type: "doc", id: "how-tos/index" },
          items: [
            "how-tos/fix-ms-teams",
            "how-tos/fix-connectivity",
            "how-tos/fix-windows-hardware-issues",
          ],
        },

        {
          type: "category",
          label: "Gists",
          collapsed: true,
          link: { type: "generated-index", slug: "/gists", description: "Quick examples, utilities, and demos." },
          items: [
            "gists/gists-git",
            "gists/gists-powershell",
            {
              type: "category",
              label: "Extras",
              collapsed: true,
              link: { type: "generated-index", slug: "/extras" },
              items: ["gists/extras/quick-responses", "gists/extras/misc"],
            },
          ],
        },
      ],
    },

    
    {
      type: "category",
      label: "DevOps",
      collapsed: true,
      link: { type: "doc", id: "devops/index" },
      items: [
        {
          type: "category",
          label: "Microsoft 365",
          collapsed: true,
          link: { type: "doc", id: "devops/admin-center/index" },
          items: [
            "devops/admin-center/emergency-accounts",
            {
              type: "category",
              label: "Trainings",
              description: "Admin & User guides",
              link: { type: "generated-index", slug: "devops/admin-center/training" },
              items: [
                "devops/admin-center/training/email-management",
                "devops/admin-center/training/install-via-intune",
                "devops/admin-center/training/conditional-access",
              ],
            },
          ],
        },

        {
          type: "category",
          label: "User Stories",
          collapsed: true,
          link: { type: "doc", id: "devops/user-stories/index" },
          items: [
            "devops/user-stories/ticket-refinement",
            "devops/user-stories/ticket-priority",
            "devops/user-stories/service-level-agreement",
          ],
        },

        {
          type: "category",
          label: "Snippets",
          collapsed: true,
          link: { type: "doc", id: "devops/snippets/index" },
          items: [
            "devops/snippets/tech-notes",
            "devops/snippets/email-templates",
          ],
        },

        "devops/glossary",
      ],
    },

    {
      type: "category",
      label: "Configuration",
      collapsed: true,
      link: { type: "doc", id: "configs/index" },
      items: [
        "configs/guides/docs/create-doc",
        "configs/guides/docs/docs-create-page",
        "configs/guides/docs/blog",
        {
          type: "category",
          label: "Deployment",
          collapsed: true,
          link: { type: "generated-index", slug: "/deployment", description: "Deployment configuration (GitHub & Cloudflare)" },
          items: [
            "configs/guides/deployment/deploy-cloudflare",
            "configs/guides/deployment/deploy-github",
          ],
        },

        {
          type: "category",
          label: "Plugins",
          collapsed: true,
          link: { type: "generated-index", slug: "/plugins" },
          items: ["configs/guides/plugins/plugins-algolia"],
        },

        {
          type: "category",
          label: "Configs",
          collapsed: true,
          link: { type: "generated-index", slug: "/guides", description: "Guidelines for creating docs, pages, and blog articles." },
          items: [],
        },
      ],
    },
    {
      type: "category",
      label: "System Administration",
      collapsed: true,
      link: {
        type: "generated-index",
        slug: "/system-administration",
        description: "Guides and best practices for System Admin. ",
      },
      items: [
        {
          type: "autogenerated",
          dirName:"system-administration"
        },
      ]
    },
  ],
  
  learnSidebar: [
    "learn",
    {
      type: "autogenerated",
      dirName: "learn"
    },

  ]

};

export default sidebars;
