/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],



  projectSidebar: [
    'introduction',
    'this-doc',

    {
      type: "category",
      label: "Projects",
      collapsed: true,
      collapsible: true,
      link: {
        type: "doc",
        id: "projects/index",
      },
      items: [
        "projects/capstone",
        "projects/python-starters",
        "projects/kitimi"
      ]
    }
    
  ],

  snippetSidebar : [
    
    {
      type: "category",
      label: "Snippets",
      collapsed: false,
      collapsible: false,

      link: {
        id: "snippets/index",
        type: "doc",
      },
      items: [
        "snippets/freq-cli",
        "snippets/space-time"
      ]
    },
    
    {
      type: "category",
      label: "Crash Dummies",
      collapsible: true,
      collapsed: true,
      link: {
        type: "generated-index",
        title: "Crash Dummies",
        description: "All about test dummies.",

        
      },
      items: [
        'snippets/foo-equations'
      ]
    }
  ],

  tutorialSidebar: [

    "tutorials/index",

    {
      type: 'category',
      label: 'Docusaurus',
      collapsed: true,
      collapsible: true,
      link: {
        type: "doc",
        id: "tutorials/docusaurus/index",
      },
      items: [
        "tutorials/docusaurus/create-a-document",
        "tutorials/docusaurus/create-a-page",
        "tutorials/docusaurus/create-a-blog-post",
        "tutorials/docusaurus/deploy-your-site",
        "tutorials/docusaurus/markdown-features",
        "tutorials/docusaurus/manage-docs-versions",
        "tutorials/docusaurus/translate-your-site",
        "tutorials/docusaurus/congratulations",
        "tutorials/docusaurus/custom-config",

      ],
      
    },
  ],
   

  // But you can create a sidebar manually
  
 /* tutorialSidebar: [
    'tutorials/index',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],*/
   
};

export default sidebars;
